// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYzSogBx7ubd2GH-I4QuxRYKOcxYlM1-8',
    appId: '1:177146363436:web:23400cf01abbb45de6db89',
    messagingSenderId: '177146363436',
    projectId: 'fishing-with-us',
    authDomain: 'fishing-with-us.firebaseapp.com',
    storageBucket: 'fishing-with-us.firebasestorage.app',
    measurementId: 'G-26SC2S3ZC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOp17qSKB1cPhOHNUSzHxoFnc-s5O5ASo',
    appId: '1:177146363436:android:b931793f4f12a56be6db89',
    messagingSenderId: '177146363436',
    projectId: 'fishing-with-us',
    storageBucket: 'fishing-with-us.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC94gaSRf6GU8yH9smbj6fER0UBq11ZK0',
    appId: '1:177146363436:ios:5301c0ea464d5f9ee6db89',
    messagingSenderId: '177146363436',
    projectId: 'fishing-with-us',
    storageBucket: 'fishing-with-us.firebasestorage.app',
    iosBundleId: 'com.example.fishingWithUs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC94gaSRf6GU8yH9smbj6fER0UBq11ZK0',
    appId: '1:177146363436:ios:5301c0ea464d5f9ee6db89',
    messagingSenderId: '177146363436',
    projectId: 'fishing-with-us',
    storageBucket: 'fishing-with-us.firebasestorage.app',
    iosBundleId: 'com.example.fishingWithUs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYzSogBx7ubd2GH-I4QuxRYKOcxYlM1-8',
    appId: '1:177146363436:web:0301d956825c9fb7e6db89',
    messagingSenderId: '177146363436',
    projectId: 'fishing-with-us',
    authDomain: 'fishing-with-us.firebaseapp.com',
    storageBucket: 'fishing-with-us.firebasestorage.app',
    measurementId: 'G-SLELDLH1QV',
  );
}
